:tests: ../../test/groovy/com/github/jengelman/gradle/plugins/shadow
== Introduction

Shadow is a Gradle plugin for combining dependency classes and resources with a project's into a single
output Jar.
The combined Jar is often referred to a __fat-jar__ or __uber-jar__.
Shadow utilizes `JarInputStream` and `JarOutputStream` to efficiently process dependent libraries
into the output jar without incurring the I/O overhead of expanding the jars to disk.

=== Benefits of Shadow

Shadowing a project output has 2 major use cases:

. Creating an __executable__ JAR distribution
. Bundling and relocating common dependencies in libraries to avoid classpath conflicts

==== Executable Distributions

Executable distribution is the main use case for __application__ developers.
The goal of an executable distribution is a single file that can be deployed and executed/run in the runtime
environment.
In the case of Shadow, this is a single __uber__ or __fat__ JAR.
The JAR file contains all the application code and dependent libraries to execute (not including the standard JVM
libraries).
The shadow JAR does **not** include the JRE itself.
It must be available on the target system.

Executable JARs contain a JAR MANIFEST that specifies the application Main Class.
This allows the application to be started with a single command:

[source, bash, subs="verbatim,attributes"]
----
$ java -jar application-shadow.jar
----

==== Library Bundling

Dependency bundling and relocation is the main use case for __library__ authors.
The goal of a bundled library is to create a pre-packaged dependency for other libraries or applications to utilize.
Often in these scenarios, a library may contain a dependency that a downstream library or application also uses.
In __some__ cases, different versions of this common dependency can cause an issue in either the upstream library or
the downstream application.
These issues often manifest themselves as binary incompatibilities in either the library or application code.

By utilizing Shadow's ability to __relocate__ the package names for dependencies, a library author can ensure that the
library's dependencies will not conflict with the same dependency being declared by the downstream application.

include::01-getting-started.adoc[]
