== Change Log

[discrete]
=== v2.0.0 (Unreleased)

* **Breaking Change!** Restrict Plugin to Gradle 3.0+
* **Breaking Change!** Build with Java 7
* **Breaking Change!** Updated `Transformer` interface to accept `TransformerContext` object instead of individual values
* **Breaking Change!** Updated `Relocator` interface to accept `RelocatePathContext` and `RelocateClassContext` objects
* **Breaking Change!** Distribution tasks `distShadowZip` and `distShadowTar` have been removed and replaced with the standard `shadowDistZip` and `shadowDistTar` from the Gradle Distribution plugin.
* **Breaking Change!** The `installShadowApp` task has been removed and replaced with the standard `installShadowDist` task from the Gradle Distribution plugin.
* **Breaking Change!** The new `installShadowDist` task outputs to `build/install/<project name>-shadow` per the standard (formerly was `build/installShadow`)
* __NEW__ Introducing `ConfigureShadowRelocation` task and `com.github.johnrengelman.shadow-plugin` plugin to automatically configure package relocation for Gradle plugins.
* __NEW__ Integration with Gradle Build Scans. When running a `ShadowJar` task with Build Scans, custom values including dependencies merged anc package relocations are published in the scan.
* Build Shadow w/ Shadow. This will help prevent any future classpath conflicts with Gradle.
* Replace `startShadowScripts` tasks with Gradle's built-in `CreateStartScripts` type.
* Build with Gradle 3.1
* https://github.com/marcphilipp[Marc Philipp] - Add `keyTransformer` property to `PropertiesFileTransformer`

[discrete]
=== v1.2.4
* Don't resolve dependency configurations during config phase (https://github.com/johnrengelman/shadow/issues/129[Issue #128])
* Build plugin with Gradle 2.14
* Fix docs regarding inheriting Jar manifest (https://github.com/johnrengelman/shadow/issues/251[Issue #251])
* https://github.com/ethankhall[Ethan Hall] - Support projects that configure uploading to Ivy repositories (https://github.com/johnrengelman/shadow/pull/256[Pull Request #256])
* Force task to depend on dependency configuration (https://github.com/johnrengelman/shadow/issues/152[Issue #152])
* Do not explode ZIP files into shadow jar (https://github.com/johnrengelman/shadow/issues/196[Issue #196])
* https://github.com/jszakmeister[John Szakmeister] - Preserve timestamps on merged jar entries (https://github.com/johnrengelman/shadow/pull/260[Pull Request #260])

[discrete]
=== v1.2.3

* Support for Gradle 2.11-rc-1 (https://github.com/johnrengelman/shadow/issues/177[Issue #177])
* Convert internal framework to https://docs.gradle.org/current/userguide/test_kit.html[Gradle TestKit]
* https://github.com/fkorotkov[Fedor Korotkov] - Use BufferedOutputStream when writing the Zip file (https://github.com/johnrengelman/shadow/pull/171[PR #171])
* https://github.com/hbchai[Haw-Bin Chai] - Quote Jar path in Windows start script as it may contain spaces (https://github.com/johnrengelman/shadow/pull/170[PR #170])
* https://github.com/siordache[Serban Iordache] - Evaluate relocation specs when merging service descriptors (https://github.com/johnrengelman/shadow/pull/165[PR #165])

[discrete]
=== v1.2.2

* https://github.com/Minecrell[Minecrell] - Gradle 2.5 compatibility (https://github.com/johnrengelman/shadow/issues/147[Issue #147])

[discrete]
=== v1.2.1

* Apply package relocations to dependency resources (https://github.com/johnrengelman/shadow/issues/114[Issue #114])

[discrete]
=== v1.2.0

* Re-organize some code to remove need for forcing the Gradle API ClassLoader to allow the `org.apache.tools.zip` package.
* Upgrade JDOM library from 1.1 to 2.0.5 (change dependency from `jdom:jdom:1.1` to `org.jdom:jdom2:2.0.5`) (https://github.com/johnrengelman/shadow/issues/98[Issue #98])
* Convert ShadowJar.groovy to ShadowJar.java to workaround binary incompatibility introduced by Gradle 2.2 ((https://github.com/johnrengelman/shadow/issues/106[Issue #106])
* Updated ASM library to `5.0.3` to support JDK8 (https://github.com/johnrengelman/shadow/issues/97[Issue #97])
* Allows for regex pattern matching in the `dependency` string when including/excluding (https://github.com/johnrengelman/shadow/issues/83[Issue #83])
* Apply package relocations to resource files (https://github.com/johnrengelman/shadow/issues/93[Issue #93])

[discrete]
=== v1.1.2

* fix bug in `runShadow` where dependencies from the `shadow` configuration are not available (https://github.com/johnrengelman/shadow/issues/94[Issue #94])

[discrete]
=== v1.1.1

* Fix bug in `'createStartScripts'` task that was causing it to not execute `'shadowJar'` task (https://github.com/johnrengelman/shadow/issues/90[Issue #90])
* Do not include `null` in ShadowJar Manifest `'Class-Path'` value when `jar` task does not specify a value for it. (https://github.com/johnrengelman/shadow/issues/92[Issue #92])
* ShadowJar Manifest `'Class-Path'` should reference jars from `'shadow'` config as relative to location of `shadowJar` output (https://github.com/johnrengelman/shadow/issues/91[Issue #91])

[discrete]
=== v1.1.0

* **Breaking Change!** Fix leaking of `shadowJar.manifest` into `jar.manifest`. (https://github.com/johnrengelman/shadow/issues/82[Issue #82])
  To simplify behavior, the `shadowJar.appendManifest` method has been removed. Replace uses with `shadowJar.manifest`
* `ShadowTask` now has a `configurations` property that is resolved to the files in the resolved configuration before
  being added to the copy spec. This allows for an easier implementation for filtering. The default 'shadowJar' task
  has the convention of adding the `'runtime'` scope to this list. Manually created instances of `ShadowTask` have no
  configurations added by default and can be configured by setting `task.configurations`.
* Properly configure integration with the `'maven'` plugin when added. When adding `'maven'` the `'uploadShadow'` task
  will now properly configure the POM dependencies by removing the `'compile'` and `'runtime'` configurations from the
  POM and adding the `'shadow'` configuration as a `RUNTIME` scope in the POM. This behavior matches the behavior when
  using the `'maven-publish'` plugin.
* https://github.com/mhurne[Matt Hurne] - Allow `ServiceFileTransformer` to specify include/exclude patterns for
  files within the configured path to merge.
* https://github.com/mhurne[Matt Hurne] - Added `GroovyExtensionModuleTransformer` for merging Groovy Extension module
  descriptor files. The existing `ServiceFileTransformer` now excludes Groovy Extension Module descriptors by default.
* `distShadowZip` and `distShadowZip` now contain the shadow library and run scripts instead of the default from the `'application'` plugin (https://github.com/johnrengelman/shadow/issues/89[Issue #89])

[discrete]
=== v1.0.3

* Make service files root path configurable for `ServiceFileTransformer` (https://github.com/johnrengelman/shadow/issues/72[Issue #72])
* https://github.com/aalmiray[Andres Almiray] - Added PropertiesFileTransformer (https://github.com/johnrengelman/shadow/issues/73[Issue #73])
* https://github.com/brandonkearby[Brandon Kearby] - Fixed StackOverflow when a cycle occurs in the resolved dependency graph (https://github.com/johnrengelman/shadow/pull/69[Issue #69])
* Apply Transformers to project resources (https://github.com/johnrengelman/shadow/issues/70[Issue #70]), https://github.com/johnrengelman/shadow/issues/71[Issue #71])
* Do not drop non-class files from dependencies when relocation is enabled. Thanks to https://github.com/Minecrell[Minecrell] for digging into this. (https://github.com/johnrengelman/shadow/issues/61[Issue #61])
* Remove support for applying individual sub-plugins by Id (easier maintenance and cleaner presentation in Gradle Portal)

[discrete]
=== v1.0.2

* Do not add an empty Class-Path attribute to the manifest when the `shadow` configuration contains no dependencies.
* `runShadow` now registers `shadowJar` as an input. Previously, `runShadow` did not execute `shadowJar` and an error occurred.
* Support Gradle 2.0 (https://github.com/johnrengelman/shadow/issues/66[Issue #66])
* Do not override existing 'Class-Path' Manifest attribute settings from Jar configuration. Instead combine. (https://github.com/johnrengelman/shadow/issues/65[Issue #65])

[discrete]
=== v1.0.1

* Fix issue where non-class files are dropped when using relocation (https://github.com/johnrengelman/shadow/issues/58[Issue #58])
* Do not create a `/` directory inside the output jar.
* Fix `runShadow` task to evaluate the `shadowJar.archiveFile` property at execution time. (https://github.com/johnrengelman/shadow/issues/60[Issue #60])

[discrete]
=== v1.0.0

* Previously known as v0.9.0
* All changes from 0.9.0-M1 to 0.9.0-M5
* Properly configure the ShadowJar task inputs to observe the include/excludes from the `dependencies` block. This
  allows UP-TO-DATE checking to work properly when changing the `dependencies` rules (https://github.com/johnrengelman/shadow/issues/54[Issue #54])
* Apply relocation remappings to classes and imports in source project (https://github.com/johnrengelman/shadow/issues/55[Issue #55])
* Do not create directories in jar for source of remapped class, created directories in jar for destination of remapped classes (https://github.com/johnrengelman/shadow/issues/53[Issue #53])

[discrete]
=== v0.9.0-M5

* Add commons-io to compile classpath
* Update asm library to 4.1

[discrete]
=== v0.9.0-M4

* Break plugin into multiple sub-plugins. `ShadowBasePlugin` is always applied.
  `ShadowJavaPlugin` and `ShadowApplicationPlugin` are applied in reaction to applying the `java` and `application`
  plugins respectively.
* Shadow does not applied `java` plugin automatically. `java` or `groovy` must be applied in conjunction with `shadow`.
* Moved artifact filtering to `dependencies {}` block underneath `shadowJar`. This allows better include/exclude control
  for dependencies.
* Dependencies added to the `shadow` configuration are automatically added to the `Class-Path` attribute in the manifest
  for `shadowJar`
* Applying `application` plugin and settings `mainClassName` automatically configures the `Main-Class` attribute in
  the manifest for `shadowJar`
* `runShadow` now utilizes the output of the `shadowJar` and executes using `java -jar <shadow jar file>`
* Start Scripts for shadow distribution now utilize `java -jar` to execute instead of placing all files on classpath
  and executing main class.
* Excluding/Including dependencies no longer includes transitive dependencies. All dependencies for inclusion/exclusion
  must be explicitly configured via a spec.

[discrete]
=== v0.9.0-M3

* Use commons.io FilenameUtils to determine name of resolved jars for including/excluding

[discrete]
=== v0.9.0-M2

* Added integration with `application` plugin to replace old `OutputSignedJars` task
* Fixed bug that resulted in duplicate file entries in the resulting Jar
* Changed plugin id to 'com.github.johnrengelman.shadow' to support Gradle 2.x plugin infrastructure.

[discrete]
=== v0.9.0-M1

* Rewrite based on Gradle Jar Task
* `ShadowJar` now extends `Jar`
* Removed `signedCompile` and `signedRuntime` configurations in favor of `shadow` configuration
* Removed `OutputSignedJars` task

