name: 'Deploy Site'
description: 'Deploy site to GitHub Pages'

runs:
  using: 'composite'
  steps:
    - uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: true
    - name: Prepare API documentation
      shell: bash
      run: ./gradlew dokkaHtml
    - name: Build Site
      shell: bash
      run: |
        # Don't cache it to track updates.
        pip install mkdocs-material
        mkdocs build
    - uses: actions/upload-pages-artifact@v3
      with:
        path: site
    - uses: actions/deploy-pages@v4
